name: 🐛 Bug Report
description: Found a bug? Help us fix it!
title: "[BUG] "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! This helps make the skills better for everyone.

  - type: dropdown
    id: skill
    attributes:
      label: Which skill?
      description: Which Melflin skill is having issues?
      options:
        - Smart Reminders Analyzer
        - Meeting Prep Assistant  
        - Knowledge Sync
        - Podcast → Notes
        - Other/General
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug clearly and concisely
      placeholder: "When I ran `smart-reminders analyze`, it..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      description: What should have happened instead?
      placeholder: "I expected it to..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Run `skill-name command`
        2. See error message...
        3. ...
    validations:
      required: true

  - type: textarea
    id: output
    attributes:
      label: Error output
      description: Paste any error messages or unexpected output
      placeholder: "Copy and paste the terminal output here"
      render: shell

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "macOS 14.2, Ubuntu 22.04, etc."
    validations:
      required: true

  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: "Run `node --version` to find out"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Anything else that might be helpful?
      placeholder: "This started happening after..., I'm using it with..., etc."

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Before submitting, please check:
      options:
        - label: I've searched existing issues to make sure this isn't a duplicate
          required: true
        - label: I've included all the information requested above
          required: true