name: 💡 Feature Request
    description: Suggest a new feature or improvement
    labels: ["enhancement"]
    
    body:
      - type: textarea
        id: description
        attributes:
          label: What problem would this solve?
          description: Describe the problem or limitation
        validations:
          required: true
    
      - type: textarea
        id: solution
        attributes:
          label: Proposed Solution
          description: How should it work?
        validations:
          required: true
    
      - type: textarea
        id: alternatives
        attributes:
          label: Alternatives Considered
          description: Any other solutions you've thought of?
